/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackCircle: typeof import('./src/components/BackCircle.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAggregatedVesselMovementView: typeof import('./src/components/TheAggregatedVesselMovementView.vue')['default']
    TheCommoditySelector: typeof import('./src/components/TheCommoditySelector.vue')['default']
    TheDateSelector: typeof import('./src/components/TheDateSelector.vue')['default']
    TheLocationLegend: typeof import('./src/components/TheLocationLegend.vue')['default']
    TheLocationSelector: typeof import('./src/components/TheLocationSelector.vue')['default']
    TheVesselMovementView: typeof import('./src/components/TheVesselMovementView.vue')['default']
    TheVesselSelector: typeof import('./src/components/TheVesselSelector.vue')['default']
    TheVesselTSNE: typeof import('./src/components/TheVesselTSNE.vue')['default']
    TheVesselTypeLegend: typeof import('./src/components/TheVesselTypeLegend.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
  }
}
